import { OhVueIcon, addIcons } from "oh-vue-icons";
import {
  IoLanguage,
  CoTypescript,
  IoLogoVue,
  SiGit,
  SiAdobephotoshop,
  SiAdobeaftereffects,
  CoMysql,
  CoSassAlt,
  SiHtml5,
  CoJest,
  CoDocker,
  LaNode,
  CoGraphql,
  BiBehance,
  BiGithub,
  BiLinkedin,
  BiInstagram,
  HiArrowSmLeft,
  OiFileDirectoryFill,
  OiFileDirectoryOpenFill,
  OiFileCode,
  BiBatteryCharging,
  BiBatteryFull,
  BiBatteryHalf,
  BiBattery,
} from "oh-vue-icons/icons";

addIcons(
  IoLanguage,
  CoTypescript,
  IoLogoVue,
  SiGit,
  SiAdobephotoshop,
  SiAdobeaftereffects,
  CoMysql,
  CoSassAlt,
  SiHtml5,
  CoJest,
  CoDocker,
  LaNode,
  CoGraphql,
  BiBehance,
  BiGithub,
  BiLinkedin,
  BiInstagram,
  HiArrowSmLeft,
  OiFileDirectoryFill,
  OiFileDirectoryOpenFill,
  OiFileCode,
  BiBatteryCharging,
  BiBatteryFull,
  BiBatteryHalf,
  BiBattery,
);

export default OhVueIcon;
