name: Deploy to GitHub Pages
on:
  push:
    branches:
      - new

jobs:
  deploy:
    name: Deploy to GitHub Pages
    runs-on: ubuntu-latest
    steps:
    - name: Directory ownership
      run: echo ${{secrets.DEPLOY_PASSWORD}} | sudo chown -R $USER:$USER /home/github/actions-runner/_work/jandrzejczak
    - uses: actions/checkout@master

    - name: Deploy
      uses: s0/git-publish-subdir-action@develop
      env:
        REPO: self
        BRANCH: gh-pages
        FOLDER: dist
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        TARGET_DIR: /
